### ISSUE TITLE
Schema support in REST framework 3.4

### ISSUE THREAD

**Issue by tomchristie** [manosim/django-rest-framework-docs#98]
Just a quick note to mention that I've started working on built-in schema support in REST framework 3.4.

Pull request: https://github.com/tomchristie/django-rest-framework/pull/4179
Upcoming new tutorial section: https://github.com/tomchristie/django-rest-framework/blob/schema-support/docs/tutorial/7-schemas-and-client-libraries.md

I think the client library support in particular is a big deal, and using Core API as the internal representation format is a necessary part of that.

This'll be relevant to `django-rest-framework-docs` because there will be built-in introspection, and this pacakge could then just rely on the `coreapi.Document` object that it returns and render that into the docs.

Raising this here and against [the swagger package](https://github.com/marcgibbons/django-rest-swagger/issues/453) just to make you folks aware that this is in the works / open the conversation / invite feedback etc...

Cheers!

**Comment by debnet** [comment]
Hurray! \o/
